'use client';

import { useEffect, useState } from 'react';
import { Glass } from '../../components/ui';
import { searchUsers } from '../../lib/supabaseData';
import { getValidUrl } from '../../lib/apiUrl';

export default function AdminPage() {
  const [stats, setStats] = useState({ total_users: '-', total_posts: '-', pending_reports: '-' }); const [users, setUsers] = useState([]); const [allUsers, setAllUsers] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const token = localStorage.getItem('aero_token'); const headers = { Accept: 'application/json', Authorization: `Bearer ${token || ''}` }; Promise.all([fetch(getValidUrl('admin/stats'), { headers }), fetch(getValidUrl('admin/users'), { headers })]).then(async ([statsResponse, usersResponse]) => { if (!statsResponse.ok || !usersResponse.ok) throw new Error('Admin access required'); const statsData = await statsResponse.json(); const usersData = await usersResponse.json(); const initialUsers = usersData.data || usersData.users || usersData || []; setStats(statsData.data || statsData); setAllUsers(initialUsers); setUsers(initialUsers); }).catch((caught) => setError(caught.message)); }, []);
  useEffect(() => { const trimmed = search.trim(); if (!trimmed) { setUsers(allUsers); return; } let cancelled = false; const timer = setTimeout(async () => { const matches = await searchUsers(trimmed); if (!cancelled) setUsers(matches); }, 300); return () => { cancelled = true; clearTimeout(timer); }; }, [search, allUsers]);
  const filtered = users;
  return <><div className="aero-bg" aria-hidden="true"><span className="aero-glow aero-glow-one" /><span className="aero-glow aero-glow-two" /></div><main className="mx-auto max-w-[1120px] px-4 py-8 sm:px-8"><header className="mb-6 rounded-[20px] border border-white/60 bg-white/65 p-6 shadow-glass backdrop-blur-2xl"><a href="/" className="text-sm text-[#0A84FF]">&larr; Back to Aero</a><h1 className="mt-2 text-3xl font-bold">Admin Dashboard</h1><span className="mt-2 inline-flex rounded-full bg-[#0A84FF]/10 px-3 py-1 text-xs font-bold text-[#0A84FF]">Admin</span></header>{error && <p className="mb-4 rounded-2xl bg-[#FF3B30]/10 p-4 text-sm text-[#FF3B30]">{error}</p>}<section className="mb-6 grid gap-4 sm:grid-cols-3">{[['Total Users', stats.total_users], ['Total Posts', stats.total_posts], ['Pending Reports', stats.pending_reports]].map(([label, value]) => <Glass key={label} className="rounded-[20px] p-5"><span className="text-sm text-[#65676b]">{label}</span><strong className="mt-2 block text-3xl">{value}</strong></Glass>)}</section><Glass className="mb-6 rounded-[20px] p-5"><h2 className="mb-4 text-xl font-bold">Users</h2><input value={search} onChange={(event) => setSearch(event.target.value)} className="mb-4 w-full rounded-2xl border border-white/70 bg-white/30 px-4 py-3 outline-none focus:border-[#0A84FF]" placeholder="Search by username or email" />{filtered.length ? <div className="divide-y divide-black/10">{filtered.map((user) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><strong>@{user.username}</strong><span className="text-sm text-[#65676b]">{user.role || 'user'}</span><span className="text-sm">{user.is_banned ? 'Banned' : 'Active'}</span></div>)}</div> : <p className="text-[#65676b]">No matching users.</p>}</Glass><Glass className="rounded-[20px] p-5"><h2 className="mb-4 text-xl font-bold">Pending Reports</h2><p className="text-[#65676b]">Moderation queue is connected to the existing API.</p></Glass></main></>;
}
